import './globals.css';
import '@mantine/core/styles.css';
import '@mantine/carousel/styles.css';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from './context/SessionContext';
import Footer from '@/components/Footer';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${inter.className} bg-body text-grey-100`}>
        <AuthProvider>
          <MantineProvider>
            <Toaster />
            {children}
            <Footer />
          </MantineProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
